/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stepsHunterSol from "./StepsHunter.sol";
export type { stepsHunterSol };
export type { ERC20Token } from "./ERC20Token";
export type { ERC721OnChainMetadata } from "./ERC721OnChainMetadata";
export type { StepsHunterNft } from "./StepsHunterNft";
