/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automationRegistryInterface12Sol from "./AutomationRegistryInterface1_2.sol";
export type { automationRegistryInterface12Sol };
export type { AutomationCompatibleInterface } from "./AutomationCompatibleInterface";
export type { ChainlinkRequestInterface } from "./ChainlinkRequestInterface";
export type { ENSInterface } from "./ENSInterface";
export type { LinkTokenInterface } from "./LinkTokenInterface";
export type { OperatorInterface } from "./OperatorInterface";
export type { OracleInterface } from "./OracleInterface";
export type { OwnableInterface } from "./OwnableInterface";
export type { PointerInterface } from "./PointerInterface";
